export enum ErrorCode {
    // Auth Validation
    MUST_BE_STRING = "MUST_BE_STRING",
    MUST_BE_INT = "MUST_BE_INT",
    MUST_BE_EMAIL = "MUST_BE_EMAIL",
    USERNAME_SHORT_LENGTH = "USERNAME_SHORT_LENGTH",
    USERNAME_LONG_LENGTH = "USERNAME_LONG_LENGTH",
    USERNAME_INVALID_FORMAT = "USERNAME_INVALID_FORMAT",
    PASSWORD_SHORT_LENGTH = "PASSWORD_SHORT_LENGTH",
    PASSWORD_LONG_LENGTH = "PASSWORD_LONG_LENGTH",
    FIRSTNAME_SHORT_LENGTH = "FIRSTNAME_SHORT_LENGTH",
    FIRSTNAME_LONG_LENGTH = "FIRSTNAME_LONG_LENGTH",
    LASTNAME_SHORT_LENGTH = "LASTNAME_SHORT_LENGTH",
    LASTNAME_LONG_LENGTH = "LASTNAME_LONG_LENGTH",

    // Auth Service
    USERNAME_TAKEN = "USERNAME_TAKEN",
    NOT_EXISTING_USER = "NOT_EXISTING_USER",
    BAD_CREDENTIALS = "BAD_CREDENTIALS",
    ALREADY_AUTHORIZED = "ALREADY_AUTHORIZED",
    INVALID_TOKEN = "INVALID_TOKEN",
    REFRESH_TOKEN_INVALID = "REFRESH_TOKEN_INVALID",
    CANNOT_SHUTDOWN_CURRENT_SESSION = "CANNOT_SHUTDOWN_CURRENT_SESSION",
    INVALID_SESSION = "INVALID_SESSION",
    PASSWORDS_MUST_BE_DIFFERENT = "PASSWORDS_MUST_BE_DIFFERENT",
    OLD_PASSWORD_INVALID = "OLD_PASSWORD_INVALID",
    EMAIL_ALREADY_TAKEN = "EMAIL_ALREADY_TAKEN",
    EMAIL_ALREADY_HAVING = "EMAIL_ALREADY_HAVING",
    INCORRECT_VERIFY_CODE = "INCORRECT_VERIFY_CODE",
    MAIN_ALREADY_SENT = "MAIN_ALREADY_SENT",
    NOT_FOUND_USER_WITH_THIS_EMAIL = "NOT_FOUND_USER_WITH_THIS_EMAIL",
    INCORRECT_CODE = "INCORRECT_CODE",
    ATTEMPTS_OVER = "ATTEMPTS_OVER",
    CODE_NOT_VERIFIED_OR_EXPIRED = "CODE_NOT_VERIFIED_OR_EXPIRED",

    // Posts Service
    INCORRECT_CONTENT_LENGTH = "INCORRECT_CONTENT_LENGTH",
    INVALID_POST = "INVALID_POST",

    // Comments Service
    INVALID_POST_OR_REPLY = "INVALID_POST_OR_REPLY",
    INVALID_COMMENT = "INVALID_COMMENT",

    // Follows Service
    ALREADY_FOLLOWED = "ALREADY_FOLLOWED",
    NOT_FOLLOWED = "NOT_FOLLOWED",
    THIS_IS_YOU = "THIS_IS_YOU",
    INVALID_USER = "INVALID_USER",

    // Common DTO's
    INVALID_TAKE_VALUE = "INVALID_TAKE_VALUE",

    // Uploads
    INVALID_FILE_FORMAT = "INVALID_FILE_FORMAT",
    FILE_NOT_FOUND = "FILE_NOT_FOUND",
    FILE_TOO_LARGE = "FILE_TOO_LARGE",

    // Other
    NOT_FOUND = "NOT_FOUND",
    UNKNOWN_ERROR = "UNKNOWN_ERROR",
    SERVER_ERROR = "SERVER_ERROR",
    BAD_REQUEST = "BAD_REQUEST",
    SOMETHING_WENT_WRONG = "SOMETHING_WENT_WRONG"
}