export enum ErrorCode {
    // Auth Validation
    MUST_BE_STRING = "MUST_BE_STRING",
    MUST_BE_INT = "MUST_BE_INT",
    USERNAME_SHORT_LENGTH = "USERNAME_SHORT_LENGTH",
    USERNAME_LONG_LENGTH = "USERNAME_LONG_LENGTH",
    USERNAME_INVALID_FORMAT = "USERNAME_INVALID_FORMAT",
    PASSWORD_SHORT_LENGTH = "PASSWORD_SHORT_LENGTH",
    PASSWORD_LONG_LENGTH = "PASSWORD_LONG_LENGTH",
    FIRSTNAME_SHORT_LENGTH = "FIRSTNAME_SHORT_LENGTH",
    FIRSTNAME_LONG_LENGTH = "FIRSTNAME_LONG_LENGTH",
    LASTNAME_SHORT_LENGTH = "LASTNAME_SHORT_LENGTH",
    LASTNAME_LONG_LENGTH = "LASTNAME_LONG_LENGTH",

    // Auth Service
    USERNAME_TAKEN = "USERNAME_TAKEN",
    NOT_EXISTING_USER = "NOT_EXISTING_USER",
    INVALID_PASSWORD = "INVALID_PASSWORD",
    ALREADY_AUTHORIZED = "ALREADY_AUTHORIZED",
    INVALID_TOKEN = "INVALID_TOKEN" ,
    REFRESH_TOKEN_INVALID = "REFRESH_TOKEN_INVALID",
    CANNOT_SHUTDOWN_CURRENT_SESSION = "CANNOT_SHUTDOWN_CURRENT_SESSION",
    INVALID_SESSION = "INVALID_SESSION",

    // Common DTO's
    INVALID_PAGE_VALUE = "INVALID_PAGE_VALUE",
    INVALID_PER_PAGE_VALUE = "INVALID_PER_PAGE_VALUE",

    // Other
    NOT_FOUND = "NOT_FOUND",
    UNKNOWN_ERROR = "UNKNOWN_ERROR"
}